name: Check semantic PR
description: Check pull request titles and commit messages to check conventional commit standards
author: Beez Innovation Labs
inputs:
  token:
    required: true
    description: Token to access the repository
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
